### ISSUE TITLE
Error while installing Peakseq

### ISSUE THREAD

**Issue by aarthi-mohan** [gersteinlab/PeakSeq#1]
Hi, 

I have gcc version 4.4.7 20120313, and I get the following error while trying to run 'make' in linux 

src/lib/utils/ansi_string/ansi_string.cpp: In static member function ‘static char\* t_string::get_alphanumeric(char*)’:
src/lib/utils/ansi_string/ansi_string.cpp:121: error: ‘memset’ was not declared in this scope

Earlier, I had a error in peakseq.cpp file,
src/genomics/chip_seq/peak_selector/peakseq.cpp:67: error: ‘strlen’ was not declared in this scope
So, I included #include <cstring> in peakseq.c and that error vanished.

Appreciate your help!

Thanks,
Aarthi

**Comment by ozgunharmanci** [comment]
This should be fixed now.
